version: '3.8'

services:
  backend:
    image: backend
    build:
      context: ./back/src
      dockerfile: Dockerfile
    ports:
      - "1414:8080"
    networks:
      - app-network
    depends_on:
      - sql_server2022

  frontend:
    image: frontend
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

  sql_server2022:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports: 
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=r00t.R00T
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
